spring.application.name=ProductCatalog
# PostgreSQL Database Connection URL (change 'mydb' to your database name)
spring.datasource.url=jdbc:postgresql://localhost:5432/productcatalog

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=chinnuKaka

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console log
spring.jpa.show-sql=true